Metrics/MethodLength:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/LineLength:
  Enabled: false
